name: xarray-tutorial
channels:
  - conda-forge
dependencies:
  - python
  # for building website:
  - jupyter-book
  - pre-commit
  # for user interface
  - dask-labextension
  - jupyterlab
  - jupyter_bokeh
  - jupyterlab-myst
  - jupyter-resource-usage
  # for default notebook kernel:
  - cartopy
  - cf_xarray
  - dask
  - datashader
  - distributed
  - gcsfs
  - geoviews-core
  - gsw
  - hvplot
  - h5netcdf
  - ipython
  - matplotlib-base
  - netcdf4
  - numpy<2
  - pint-xarray
  - pip
  - pydap
  - python-graphviz
  - pooch
  - rioxarray
  - scipy
  - sphinx-codeautolink
  - sphinxcontrib-mermaid
  - sphinx-notfound-page
  - sphinxext-rediraffe
  - s3fs
  - xarray
  - zarr
